// <auto-generated />
using System;
using MU5PrototypeProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MU5PrototypeProject.Data.MUMigrations
{
    [DbContext(typeof(MUContext))]
    [Migration("20260227013715_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("MU5PrototypeProject.Models.AdminStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminInitials")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CommunicatedProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CourseCorrectionNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NextAppointmentBooked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyToProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReferredExternally")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferredTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TeamConsult")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("AdminStatuses");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Apparatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApparatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Apparatuses");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientFolderUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DOB", "LastName", "FirstName")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApparatusID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ApparatusID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.ExerciseProp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("PropID");

                    b.ToTable("ExerciseProps");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.ExerciseSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GearBarLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadrestPosition")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StopperSetting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrapsType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ExerciseID");

                    b.ToTable("ExerciseSettings");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.PhysioInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountUsed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CommunicatedWithPhysio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CoverageAmountPerYear")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CoverageResetsDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoverageShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InsuranceCompany")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysiotherapistName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("PhysioInfos");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Prop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionID");

                    b.ToTable("Props");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionsPerWeekRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionExercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Props")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Springs")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("SessionID");

                    b.ToTable("SessionExercises");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionNotes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletedByTrainerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneralComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthMedicalHistory")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectiveFindings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectiveReports")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompletedByTrainerID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("SessionNotes");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Trainer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.AdminStatus", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithOne("AdminStatus")
                        .HasForeignKey("MU5PrototypeProject.Models.AdminStatus", "SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Exercise", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Apparatus", "Apparatus")
                        .WithMany("Exercises")
                        .HasForeignKey("ApparatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Apparatus");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.ExerciseProp", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.Prop", "Prop")
                        .WithMany("ExerciseProps")
                        .HasForeignKey("PropID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Prop");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.ExerciseSettings", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.PhysioInfo", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithOne("PhysioInfo")
                        .HasForeignKey("MU5PrototypeProject.Models.PhysioInfo", "SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Prop", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Session", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Client", "Client")
                        .WithMany("Sessions")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionExercise", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Exercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.SessionNotes", b =>
                {
                    b.HasOne("MU5PrototypeProject.Models.Trainer", "CompletedByTrainer")
                        .WithMany()
                        .HasForeignKey("CompletedByTrainerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MU5PrototypeProject.Models.Session", "Session")
                        .WithOne("SessionNotes")
                        .HasForeignKey("MU5PrototypeProject.Models.SessionNotes", "SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByTrainer");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Apparatus", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Client", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Exercise", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Prop", b =>
                {
                    b.Navigation("ExerciseProps");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Session", b =>
                {
                    b.Navigation("AdminStatus");

                    b.Navigation("Exercises");

                    b.Navigation("PhysioInfo");

                    b.Navigation("SessionNotes");
                });

            modelBuilder.Entity("MU5PrototypeProject.Models.Trainer", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
